# UI translations
translations = {
    "English": {
        "title": "QM Armor Picker",
        "subtitle": "Select resistance requirements and search for armors.",
        "color_legend": "**Color Legend**: Resistance values are colored from 🔴 Red (low) to 🟢 Green (high)",
        "language": "Language",
        "resistance_filters": "Resistance Filters",
        "enable": "Enable",
        "min_value": "Min {} Value",
        "search_button": "Search Armors",
        "results": "Results",
        "click_search": "Click 'Search Armors' to see results...",
        "no_armors": "No armors found matching the criteria.",
        "name": "Name",
        "class": "Class",
        "description": "Description",
        "durability": "Durability",
        "weight": "Weight",
        "blunt": "Blunt",
        "pierce": "Pierce",
        "lacer": "Cut",
        "fire": "Fire",
        "cold": "Cold",
        "poison": "Poison",
        "shock": "Shock",
        "beam": "Beam",
        "game_version": "Game Version",
        "no_requirements_set": "No resistance requirements set for combination search.",
        "no_combinations_found": "No armor combinations found that meet the requirements.",
        "armor_combinations": "Armor Combinations",
        "combinations_explanation": "Armor combinations that best meet resistance requirements:",
        "combination": "Combination",
        "dispersion": "Dispersion",
        "item": "Item",
        "type": "Type",
        "armor_combinations_tab": "Armor Combinations",
        "individual_armors_tab": "Individual Armors",
        "perk_invincible": "Invincible Perk (+12 all resistances)",
        "talent_all_resists": "Hardened (+10% resistances)",
        "extra_settings_markdown": "Extra Settings",
        "extra_settings_markdown_text": "Extra settings to narrow down and speed up searching",
        "extra_settings_textlevels_text": "Tech Levels",
        "selector_tech_level": "Min level",
        "extra_settings_armorclass_text": "Armor Class",
        "extra_settings_armorsubclass_text": "Armor SubClass",
        "extra_settings_armorignore_text": "Armor Ignore",
        "selector_armor_subclass_info": "All Quasimorph items are Quasi. Everything else is Default.",
        "selector_armor_categories_block_info": "These are the categories that are blocked by default as they are low tier.",

    },
    "Русский": {
        "title": "QM Подборщик Брони",
        "subtitle": "Выберите требования к сопротивлению и найдите броню.",
        "color_legend": "**Легенда цветов**: Значения сопротивления окрашены от 🔴 Красного (низкое) до 🟢 Зеленого (высокое)",
        "language": "Язык",
        "resistance_filters": "Фильтры Сопротивления",
        "enable": "Включить",
        "min_value": "Мин. {} Значение",
        "search_button": "Поиск Брони",
        "results": "Результаты",
        "click_search": "Нажмите 'Поиск Брони' для просмотра результатов...",
        "no_armors": "Броня, соответствующая критериям, не найдена.",
        "name": "Название",
        "class": "Класс",
        "description": "Описание",
        "durability": "Прочность",
        "weight": "Вес",
        "blunt": "Дробящий",
        "pierce": "Проникающий",
        "lacer": "Режущий",
        "fire": "Огонь",
        "cold": "Холод",
        "poison": "Ядовитый",
        "shock": "Электрический",
        "beam": "Лучевой",
        "game_version": "Версия Игры",
        "no_requirements_set": "Не установлены требования к сопротивлению для поиска комбинаций.",
        "no_combinations_found": "Не найдено комбинаций брони, соответствующих требованиям.",
        "armor_combinations": "Комбинации Брони",
        "combinations_explanation": "Комбинации брони, которые лучше всего соответствуют требованиям к сопротивлению:",
        "combination": "Комбинация",
        "dispersion": "Дисперсия",
        "item": "Предмет",
        "type": "Тип",
        "armor_combinations_tab": "Комбинации Брони",
        "individual_armors_tab": "Общий список брони",
        "perk_invincible": "Непобедимый (+12 ко всем сопротивлениям)",
        "talent_all_resists": "Закаленный (+10% к сопротивлениям)",
        "extra_settings_markdown": "Дополнительные настройки",
        "extra_settings_markdown_text": "Дополнительные настройки для уточнения и ускорения поиска",
        "extra_settings_textlevels_text": "Технические уровни",
        "selector_tech_level": "Минимальный уровень",
        "extra_settings_armorclass_text": "Класс брони",
        "extra_settings_armorsubclass_text": "Подкласс брони",
        "extra_settings_armorignore_text": "Игнорирование брони",
        "selector_armor_subclass_info": "Все предметы Квазиморфа являются Quasi. Всё остальное - Default.",
        "selector_armor_categories_block_info": "Это категории, которые заблокированы по умолчанию, так как они низкого уровня."

    },
    "Deutsch": {
        "title": "QM Rüstungs-Picker",
        "subtitle": "Wählen Sie Widerstandsanforderungen und suchen Sie nach Rüstungen.",
        "color_legend": "**Farblegende**: Widerstandswerte sind von 🔴 Rot (niedrig) bis 🟢 Grün (hoch) gefärbt",
        "language": "Sprache",
        "resistance_filters": "Widerstandsfilter",
        "enable": "Aktivieren",
        "min_value": "Min. {} Wert",
        "search_button": "Rüstung Suchen",
        "results": "Ergebnisse",
        "click_search": "Klicken Sie auf 'Rüstung Suchen' um Ergebnisse zu sehen...",
        "no_armors": "Keine Rüstung gefunden, die den Kriterien entspricht.",
        "name": "Name",
        "class": "Klasse",
        "description": "Beschreibung",
        "durability": "Haltbarkeit",
        "weight": "Gewicht",
        "blunt": "Stumpf",
        "pierce": "Durchschlag",
        "lacer": "Schneiden",
        "fire": "Feuer",
        "cold": "Kälte",
        "poison": "Gift",
        "shock": "Schock",
        "beam": "Strahl",
        "game_version": "Spielversion",
        "no_requirements_set": "Keine Widerstandsanforderungen für die Kombinationssuche festgelegt.",
        "no_combinations_found": "Keine Rüstungskombinationen gefunden, die den Anforderungen entsprechen.",
        "armor_combinations": "Rüstungskombinationen",
        "combinations_explanation": "Rüstungskombinationen, die den Widerstandsanforderungen am besten entsprechen:",
        "combination": "Kombination",
        "dispersion": "Streuung",
        "item": "Gegenstand", 
        "type": "Typ",
        "armor_combinations_tab": "Rüstungskombinationen",
        "individual_armors_tab": "Einzelne Rüstungen",
        "perk_invincible": "Unverwundbar (+12 alle Widerstände)",
        "talent_all_resists": "Abhärtung (+10% Widerstände)",
        "extra_settings_markdown": "Zusätzliche Einstellungen",
        "extra_settings_markdown_text": "Zusätzliche Einstellungen zur Eingrenzung und Beschleunigung der Suche",
        "extra_settings_textlevels_text": "Technische Ebenen",
        "selector_tech_level": "Min. Level",
        "extra_settings_armorclass_text": "Rüstungsart",
        "extra_settings_armorsubclass_text": "Rüstungsunterklasse",
        "extra_settings_armorignore_text": "Rüstungsignorieren",
        "selector_armor_subclass_info": "Alle Quasimorph-Artikel sind Quasi. Alles andere ist Default.",
        "selector_armor_categories_block_info": "Dies sind die Kategorien, die standardmäßig blockiert sind, da sie niedrigerer Stufe sind."

    },
    "Français": {
        "title": "QM Sélecteur d'Armure",
        "subtitle": "Sélectionnez les exigences de résistance et recherchez des armures.",
        "color_legend": "**Légende des couleurs**: Les valeurs de résistance sont colorées du 🔴 Rouge (faible) au 🟢 Vert (élevé)",
        "language": "Langue",
        "resistance_filters": "Filtres de Résistance",
        "enable": "Activer",
        "min_value": "Valeur {} Min.",
        "search_button": "Rechercher Armures",
        "results": "Résultats",
        "click_search": "Cliquez sur 'Rechercher Armures' pour voir les résultats...",
        "no_armors": "Aucune armure trouvée correspondant aux critères.",
        "name": "Nom",
        "class": "Classe",
        "description": "Description",
        "durability": "Durabilité",
        "weight": "Poids",
        "blunt": "Сontondants",
        "pierce": "Perforants",
        "lacer": "Coupe",
        "fire": "Feu",
        "cold": "Froid",
        "poison": "Toxique",
        "shock": "Choc",
        "beam": "Faisceau",
        "game_version": "Version du Jeu",
        "no_requirements_set": "Aucune exigence de résistance définie pour la recherche de combinaisons.",
        "no_combinations_found": "Aucune combinaison d'armures trouvée qui répond aux exigences.",
        "armor_combinations": "Combinaisons d'Armures",
        "combinations_explanation": "Combinaisons d'armures qui répondent le mieux aux exigences de résistance:",
        "combination": "Combinaison",
        "dispersion": "Dispersion",
        "item": "Objet",
        "type": "Type",
        "armor_combinations_tab": "Combinaisons d'Armures",
        "individual_armors_tab": "Armures Individuelles",
        "perk_invincible": "Invincible (+12 toutes résistances)",
        "talent_all_resists": "Durcissement (+10% résistances)",
        "extra_settings_markdown": "Paramètres supplémentaires",
        "extra_settings_markdown_text": "Paramètres supplémentaires pour affiner et accélérer la recherche",
        "extra_settings_textlevels_text": "Niveaux techniques",
        "selector_tech_level": "Niveau min",
        "extra_settings_armorclass_text": "Classe d'armure",
        "extra_settings_armorsubclass_text": "Sous-classe d'armure",
        "extra_settings_armorignore_text": "Ignorer l'armure",
        "selector_armor_subclass_info": "Tous les objets Quasimorph sont Quasi. Tout le reste est Default.",
        "selector_armor_categories_block_info": "Ce sont les catégories qui sont bloquées par défaut car elles sont de bas niveau."

    },
    "Español": {
        "title": "QM Selector de Armadura",
        "subtitle": "Seleccione los requisitos de resistencia y busque armaduras.",
        "color_legend": "**Leyenda de colores**: Los valores de resistencia están coloreados desde 🔴 Rojo (bajo) hasta 🟢 Verde (alto)",
        "language": "Idioma",
        "resistance_filters": "Filtros de Resistencia",
        "enable": "Habilitar",
        "min_value": "Valor {} Mín.",
        "search_button": "Buscar Armaduras",
        "results": "Resultados",
        "click_search": "Haga clic en 'Buscar Armaduras' para ver los resultados...",
        "no_armors": "No se encontraron armaduras que coincidan con los criterios.",
        "name": "Nombre",
        "class": "Clase",
        "description": "Descripción",
        "durability": "Durabilidad",
        "weight": "Peso",
        "blunt": "Daño contundente",
        "pierce": "Perforador",
        "lacer": "Corte",
        "fire": "Fuego",
        "cold": "Frío",
        "poison": "Venenoso",
        "shock": "Choque",
        "beam": "Rayo",
        "game_version": "Versión del Juego",
        "no_requirements_set": "No se han establecido requisitos de resistencia para la búsqueda de combinaciones.",
        "no_combinations_found": "No se encontraron combinaciones de armaduras que cumplan con los requisitos.",
        "armor_combinations": "Combinaciones de Armaduras",
        "combinations_explanation": "Combinaciones de armaduras que mejor cumplen con los requisitos de resistencia:",
        "combination": "Combinación",
        "dispersion": "Dispersión",
        "item": "Objeto",
        "type": "Tipo",
        "armor_combinations_tab": "Combinaciones de Armaduras",
        "individual_armors_tab": "Armaduras Individuales",
        "perk_invincible": "Invencible (+12 todas las resistencias)",
        "talent_all_resists": "Fortalecedor (+10% resistencias)",
        "extra_settings_markdown": "Configuraciones adicionales",
        "extra_settings_markdown_text": "Configuraciones adicionales para precisar y acelerar la búsqueda",
        "extra_settings_textlevels_text": "Niveles técnicos",
        "selector_tech_level": "Nivel mínimo",
        "extra_settings_armorclass_text": "Clase de armadura",
        "extra_settings_armorsubclass_text": "Subclase de armadura",
        "extra_settings_armorignore_text": "Ignorar armadura",
        "selector_armor_subclass_info": "Todos los artículos Quasimorph son Quasi. Todo lo demás es Default.",
        "selector_armor_categories_block_info": "Estas son las categorías que están bloqueadas por defecto ya que son de nivel bajo."

    },
    "Polski": {
        "title": "QM Wybieracz Zbroi",
        "subtitle": "Wybierz wymagania odporności i wyszukaj zbroje.",
        "color_legend": "**Legenda kolorów**: Wartości odporności są kolorowane od 🔴 Czerwonego (niskie) do 🟢 Zielonego (wysokie)",
        "language": "Język",
        "resistance_filters": "Filtry Odporności",
        "enable": "Włącz",
        "min_value": "Min. Wartość {}",
        "search_button": "Szukaj Zbroi",
        "results": "Wyniki",
        "click_search": "Kliknij 'Szukaj Zbroi' aby zobaczyć wyniki...",
        "no_armors": "Nie znaleziono zbroi spełniających kryteria.",
        "name": "Nazwa",
        "class": "Klasa",
        "description": "Opis",
        "durability": "Wytrzymałość",
        "weight": "Waga",
        "blunt": "Obuchowe",
        "pierce": "Przebicie",
        "lacer": "Cięcie",
        "fire": "Ogień",
        "cold": "Zimno",
        "poison": "Trujący",
        "shock": "Wstrząs",
        "beam": "Promień",
        "game_version": "Wersja Gry",
        "no_requirements_set": "Nie ustawiono wymagań odporności dla wyszukiwania kombinacji.",
        "no_combinations_found": "Nie znaleziono kombinacji zbroi spełniających wymagania.",
        "armor_combinations": "Kombinacje Zbroi",
        "combinations_explanation": "Kombinacje zbroi, które najlepiej spełniają wymagania odporności:",
        "combination": "Kombinacja",
        "dispersion": "Rozproszenie",
        "item": "Przedmiot",
        "type": "Typ",
        "armor_combinations_tab": "Kombinacje Zbroi",
        "individual_armors_tab": "Pojedyncze Zbroje",
        "perk_invincible": "Niezniszczalność (+12 wszystkie odporności)",
        "talent_all_resists": "Utwardzanie (+10% odporności)",
        "extra_settings_markdown": "Dodatkowe ustawienia",
        "extra_settings_markdown_text": "Dodatkowe ustawienia do zawężania i przyspieszania wyszukiwania",
        "extra_settings_textlevels_text": "Poziomy technologiczne",
        "selector_tech_level": "Min poziom",
        "extra_settings_armorclass_text": "Klasa zbroi",
        "extra_settings_armorsubclass_text": "Podklasa zbroi",
        "extra_settings_armorignore_text": "Ignoruj zbroję",
        "selector_armor_subclass_info": "Wszystkie przedmioty Quasimorph są Quasi. Wszystko inne to Default.",
        "selector_armor_categories_block_info": "To są kategorie, które są domyślnie zablokowane, ponieważ są niskiego poziomu."

    },
    "Türkçe": {
        "title": "QM Zırh Seçici",
        "subtitle": "Direnç gereksinimlerini seçin ve zırhları arayın.",
        "color_legend": "**Renk Açıklaması**: Direnç değerleri 🔴 Kırmızı (düşük) ile 🟢 Yeşil (yüksek) arasında renklendirilmiştir",
        "language": "Dil",
        "resistance_filters": "Direnç Filtreleri",
        "enable": "Etkinleştir",
        "min_value": "Min {} Değeri",
        "search_button": "Zırh Ara",
        "results": "Sonuçlar",
        "click_search": "Sonuçları görmek için 'Zırh Ara'ya tıklayın...",
        "no_armors": "Kriterlere uyan zırh bulunamadı.",
        "name": "İsim",
        "class": "Sınıf",
        "description": "Açıklama",
        "durability": "Dayanıklılık",
        "weight": "Ağırlık",
        "blunt": "Darbe",
        "pierce": "Delici",
        "lacer": "Kesik",
        "fire": "Ateş",
        "cold": "Soğuk",
        "poison": "Zehirli",
        "shock": "Şok",
        "beam": "Işın",
        "game_version": "Oyun Sürümü",
        "no_requirements_set": "Kombinasyon araması için direnç gereksinimleri belirlenmedi.",
        "no_combinations_found": "Gereksinimleri karşılayan zırh kombinasyonu bulunamadı.",
        "armor_combinations": "Zırh Kombinasyonları",
        "combinations_explanation": "Direnç gereksinimlerini en iyi karşılayan zırh kombinasyonları:",
        "combination": "Kombinasyon",
        "dispersion": "Dağılım",
        "item": "Eşya",
        "type": "Tür",
        "armor_combinations_tab": "Zırh Kombinasyonları",
        "individual_armors_tab": "Tekil Zırhlar",
        "perk_invincible": "Yenilmez (+12 tüm dirençler)",
        "talent_all_resists": "Sertleşme (+10% dirençler)",
        "extra_settings_markdown": "Ekstra Ayarlar",
        "extra_settings_markdown_text": "Arama işlemini daraltmak ve hızlandırmak için ek ayarlar",
        "extra_settings_textlevels_text": "Teknik Seviyeler",
        "selector_tech_level": "Min seviye",
        "extra_settings_armorclass_text": "Zırh Sınıfı",
        "extra_settings_armorsubclass_text": "Zırh Alt Sınıfı",
        "extra_settings_armorignore_text": "Zırhı Yoksay",
        "selector_armor_subclass_info": "Tüm Quasimorph eşyaları Quasi'dir. Diğer her şey Default'tır.",
        "selector_armor_categories_block_info": "Bunlar, düşük seviyede oldukları için varsayılan olarak engellenmiş kategorilerdir."

    },
    "Português Brasileiro": {
        "title": "QM Seletor de Armadura",
        "subtitle": "Selecione os requisitos de resistência e procure armaduras.",
        "color_legend": "**Legenda de cores**: Os valores de resistência são coloridos de 🔴 Vermelho (baixo) a 🟢 Verde (alto)",
        "language": "Idioma",
        "resistance_filters": "Filtros de Resistência",
        "enable": "Ativar",
        "min_value": "Valor {} Mín.",
        "search_button": "Buscar Armaduras",
        "results": "Resultados",
        "click_search": "Clique em 'Buscar Armaduras' para ver os resultados...",
        "no_armors": "Nenhuma armadura encontrada que corresponda aos critérios.",
        "name": "Nome",
        "class": "Classe",
        "description": "Descrição",
        "durability": "Durabilidade",
        "weight": "Peso",
        "blunt": "Golpe",
        "pierce": "Perfuração",
        "lacer": "Corte",
        "fire": "Fogo",
        "cold": "Frio",
        "poison": "Veneno",
        "shock": "Choque",
        "beam": "Feixe",
        "game_version": "Versão do Jogo",
        "no_requirements_set": "Nenhum requisito de resistência definido para busca de combinações.",
        "no_combinations_found": "Nenhuma combinação de armaduras encontrada que atenda aos requisitos.",
        "armor_combinations": "Combinações de Armaduras",
        "combinations_explanation": "Combinações de armaduras que melhor atendem aos requisitos de resistência:",
        "combination": "Combinação",
        "dispersion": "Dispersão",
        "item": "Item",
        "type": "Tipo",
        "armor_combinations_tab": "Combinações de Armaduras",
        "individual_armors_tab": "Armaduras Individuais",
        "perk_invincible": "Invencível (+12 todas resistências)",
        "talent_all_resists": "Enrijecimento (+10% resistências)",
        "extra_settings_markdown": "Configurações Adicionais",
        "extra_settings_markdown_text": "Configurações adicionais para restringir e acelerar a pesquisa",
        "extra_settings_textlevels_text": "Níveis Técnicos",
        "selector_tech_level": "Nível mínimo",
        "extra_settings_armorclass_text": "Classe de Armadura",
        "extra_settings_armorsubclass_text": "Subclasse de Armadura",
        "extra_settings_armorignore_text": "Ignorar Armadura",
        "selector_armor_subclass_info": "Todos os itens Quasimorph são Quasi. Todo o resto é Default.",
        "selector_armor_categories_block_info": "Estas são as categorias que estão bloqueadas por padrão, pois são de baixo nível."

    },
    "한국어": {
        "title": "QM 갑옷 선택기",
        "subtitle": "저항 요구사항을 선택하고 갑옷을 검색하세요.",
        "color_legend": "**색상 범례**: 저항 값은 🔴 빨간색(낮음)에서 🟢 녹색(높음)으로 색칠됩니다",
        "language": "언어",
        "resistance_filters": "저항 필터",
        "enable": "활성화",
        "min_value": "최소 {} 값",
        "search_button": "갑옷 검색",
        "results": "결과",
        "click_search": "결과를 보려면 '갑옷 검색'을 클릭하세요...",
        "no_armors": "기준에 맞는 갑옷을 찾을 수 없습니다.",
        "name": "이름",
        "class": "클래스",
        "description": "설명",
        "durability": "내구도",
        "weight": "무게",
        "blunt": "둔기",
        "pierce": "관통",
        "lacer": "절단",
        "fire": "불",
        "cold": "냉기",
        "poison": "독",
        "shock": "충격",
        "beam": "빔",
        "game_version": "게임 버전",
        "no_requirements_set": "조합 검색을 위한 저항 요구사항이 설정되지 않았습니다.",
        "no_combinations_found": "요구사항을 충족하는 갑옷 조합을 찾을 수 없습니다.",
        "armor_combinations": "갑옷 조합",
        "combinations_explanation": "저항 요구사항을 가장 잘 충족하는 갑옷 조합:",
        "combination": "조합",
        "dispersion": "분산",
        "item": "아이템",
        "type": "유형",
        "armor_combinations_tab": "갑옷 조합",
        "individual_armors_tab": "개별 갑옷",
        "perk_invincible": "천하무적 (+12 모든 저항)",
        "talent_all_resists": "경화 (+10% 저항)",
        "extra_settings_markdown": "추가 설정",
        "extra_settings_markdown_text": "검색을 좁히고 빠르게 하기 위한 추가 설정",
        "extra_settings_textlevels_text": "기술 수준",
        "selector_tech_level": "최소 수준",
        "extra_settings_armorclass_text": "갑옷 클래스",
        "extra_settings_armorsubclass_text": "갑옷 서브 클래스",
        "extra_settings_armorignore_text": "갑옷 무시",
        "selector_armor_subclass_info": "모든 Quasimorph 아이템은 Quasi입니다. 나머지는 Default입니다.",
        "selector_armor_categories_block_info": "이들은 기본적으로 차단된 카테고리로, 낮은 수준입니다."

    },
    "日本": {
        "title": "QM アーマーピッカー",
        "subtitle": "抵抗要件を選択して防具を検索します。",
        "color_legend": "**色の凡例**: 抵抗値は🔴赤（低）から🟢緑（高）まで色分けされています",
        "language": "言語",
        "resistance_filters": "抵抗フィルター",
        "enable": "有効化",
        "min_value": "最小{}値",
        "search_button": "防具を検索",
        "results": "結果",
        "click_search": "結果を表示するには「防具を検索」をクリックしてください...",
        "no_armors": "条件に一致する防具が見つかりませんでした。",
        "name": "名前",
        "class": "クラス",
        "description": "説明",
        "durability": "耐久性",
        "weight": "重量",
        "blunt": "打撃",
        "pierce": "突き刺し",
        "lacer": "斬撃",
        "fire": "火",
        "cold": "凍結",
        "poison": "毒",
        "shock": "ショック",
        "beam": "ビーム",
        "game_version": "ゲームバージョン",
        "no_requirements_set": "組み合わせ検索の抵抗要件が設定されていません。",
        "no_combinations_found": "要件を満たす防具の組み合わせが見つかりませんでした。",
        "armor_combinations": "防具の組み合わせ",
        "combinations_explanation": "抵抗要件を最もよく満たす防具の組み合わせ:",
        "combination": "組み合わせ",
        "dispersion": "分散",
        "item": "アイテム",
        "type": "タイプ",
        "armor_combinations_tab": "防具の組み合わせ",
        "individual_armors_tab": "個別の防具",
        "perk_invincible": "無敵 (+12 全抵抗)",
        "talent_all_resists": "硬化 (+10% 抵抗)",
        "extra_settings_markdown": "追加設定",
        "extra_settings_markdown_text": "検索を絞り込み、速度を上げるための追加設定",
        "extra_settings_textlevels_text": "技術レベル",
        "selector_tech_level": "最小レベル",
        "extra_settings_armorclass_text": "アーマークラス",
        "extra_settings_armorsubclass_text": "アーマーサブクラス",
        "extra_settings_armorignore_text": "アーマーを無視",
        "selector_armor_subclass_info": "すべてのQuasimorphアイテムはQuasiです。他のすべてはDefaultです。",
        "selector_armor_categories_block_info": "これらはデフォルトでブロックされているカテゴリで、低いティアです。"

    },
    "中国人": {
        "title": "QM 护甲选择器",
        "subtitle": "选择抗性要求并搜索护甲。",
        "color_legend": "**颜色图例**: 抗性值从🔴红色（低）到🟢绿色（高）着色",
        "language": "语言",
        "resistance_filters": "抗性过滤器",
        "enable": "启用",
        "min_value": "最小{}值",
        "search_button": "搜索护甲",
        "results": "结果",
        "click_search": '点击"搜索护甲"查看结果...',
        "no_armors": "未找到符合条件的护甲。",
        "name": "名称",
        "class": "类别",
        "description": "描述",
        "durability": "耐久度",
        "weight": "重量",
        "blunt": "钝击",
        "pierce": "穿刺",
        "lacer": "切割",
        "fire": "火焰",
        "cold": "寒冷",
        "poison": "有毒",
        "shock": "电的",
        "beam": "辐射的",
        "game_version": "游戏版本",
        "no_requirements_set": "未设置组合搜索的抗性要求。",
        "no_combinations_found": "未找到满足要求的护甲组合。",
        "armor_combinations": "护甲组合",
        "combinations_explanation": "最符合抗性要求的护甲组合:",
        "combination": "组合",
        "dispersion": "离散度",
        "item": "物品",
        "type": "类型",
        "armor_combinations_tab": "护甲组合",
        "individual_armors_tab": "单个护甲",
        "perk_invincible": "无敌无敌天赋 (+12 所有抗性)",
        "talent_all_resists": "皮糙肉厚 (+10% 抗性)",
        "extra_settings_markdown": "额外设置",
        "extra_settings_markdown_text": "缩小和加速搜索的额外设置",
        "extra_settings_textlevels_text": "技术水平",
        "selector_tech_level": "最小等级",
        "extra_settings_armorclass_text": "护甲类别",
        "extra_settings_armorsubclass_text": "护甲子类别",
        "extra_settings_armorignore_text": "忽略护甲",
        "selector_armor_subclass_info": "所有的Quasimorph物品都是Quasi。其他的都是Default。",
        "selector_armor_categories_block_info": "这些是默认被阻止的类别，因为它们是低级别的。"
    }
}